-- Tabla 1: Agencia
CREATE TABLE AGENCIA (
	CODIGO_AGENCIA VARCHAR(10) NOT NULL PRIMARY KEY,
	PRIMER_NOMBRE VARCHAR(100) NOT NULL,
	SEGUNDO_NOMBRE VARCHAR(100) NULL,
	MUNICIPIO VARCHAR(100) NOT NULL,
	CALLE VARCHAR(150) NOT NULL,
	BARRIO VARCHAR(100) NULL,
	FECHA_APERTURA DATE NOT NULL CHECK (FECHA_APERTURA <= CURRENT_DATE)
);

-- Tabla 2: Asociado
CREATE TABLE ASOCIADO (
	CEDULA_ASOCIADO VARCHAR(15) NOT NULL PRIMARY KEY,
	PRIMER_NOMBRE VARCHAR(100) NOT NULL,
	SEGUNDO_NOMBRE VARCHAR(100) NULL,
	APELLIDO VARCHAR(100) NOT NULL,
	FECHA_NAC DATE NOT NULL,
	MUNICIPIO VARCHAR(100) NOT NULL,
	CALLE VARCHAR(150) NOT NULL,
	BARRIO VARCHAR(100) NULL,
	FECHA_INGRESO DATE NOT NULL CHECK (FECHA_INGRESO <= CURRENT_DATE),
	ESTADO VARCHAR(20) NOT NULL CHECK (ESTADO IN ('activo', 'suspendido', 'retirado'))
);

-- Tabla 3: Agencia_Telefono
CREATE TABLE AGENCIA_TELEFONO (
	ID_TEL_AGENCIA SERIAL NOT NULL PRIMARY KEY,
	CODIGO_AGENCIA VARCHAR(10) NOT NULL,
	TELEFONO VARCHAR(15) NOT NULL,
	FOREIGN KEY (CODIGO_AGENCIA) REFERENCES AGENCIA (CODIGO_AGENCIA)
);

-- Tabla 4: Asociado_Telefono
CREATE TABLE ASOCIADO_TELEFONO (
	ID_TEL_ASOCIADO SERIAL NOT NULL PRIMARY KEY,
	CEDULA_ASOCIADO VARCHAR(15) NOT NULL,
	TELEFONO VARCHAR(15) NOT NULL,
	FOREIGN KEY (CEDULA_ASOCIADO) REFERENCES ASOCIADO (CEDULA_ASOCIADO)
);

-- Tabla 5: Asociado_Correo
CREATE TABLE ASOCIADO_CORREO (
	ID_COR_ASOCIADO SERIAL NOT NULL PRIMARY KEY,
	CEDULA_ASOCIADO VARCHAR(15) NOT NULL,
	CORREO VARCHAR(100) NOT NULL,
	FOREIGN KEY (CEDULA_ASOCIADO) REFERENCES ASOCIADO (CEDULA_ASOCIADO)
);

-- Tabla 6: Fundador
CREATE TABLE FUNDADOR (
	CEDULA_ASOCIADO VARCHAR(15) NOT NULL PRIMARY KEY,
	NUMERO_ACTA VARCHAR(20) NOT NULL,
	ANIO_RECONOCIMIENTO INTEGER NOT NULL,
	DES_BENEFICIOS TEXT NULL,
	FOREIGN KEY (CEDULA_ASOCIADO) REFERENCES ASOCIADO (CEDULA_ASOCIADO)
);

-- Tabla 7: Beneficiarios
CREATE TABLE BENEFICIARIOS (
	DOCUMENTO_BENEF VARCHAR(20) NOT NULL PRIMARY KEY,
	PRIMER_NOMBRE VARCHAR(100) NOT NULL,
	SEGUNDO_NOMBRE VARCHAR(100) NULL,
	APELLIDO VARCHAR(100) NOT NULL,
	PARENTESCO VARCHAR(50) NOT NULL CHECK (
		PARENTESCO IN (
			'conyuge',
			'hijo',
			'padre',
			'madre',
			'hermano',
			'otro'
		)
	),
	PORCENTAJE_PARTICIPACION NUMERIC(5, 2) NOT NULL CHECK (
		PORCENTAJE_PARTICIPACION > 0
		AND PORCENTAJE_PARTICIPACION <= 100
	),
	CEDULA_ASOCIADO VARCHAR(15) NOT NULL,
	FOREIGN KEY (CEDULA_ASOCIADO) REFERENCES ASOCIADO (CEDULA_ASOCIADO)
);

-- Tabla 8: Beneficiarios_telefono
CREATE TABLE BENEFICIARIOS_TELEFONO (
	ID_TEL_BENEFICIARIOS SERIAL NOT NULL PRIMARY KEY,
	DOCUMENTO_BENEF VARCHAR(20) NOT NULL,
	TELEFONO VARCHAR(15) NOT NULL,
	FOREIGN KEY (DOCUMENTO_BENEF) REFERENCES BENEFICIARIOS (DOCUMENTO_BENEF)
);

-- Tabla 9: Empleado
CREATE TABLE EMPLEADO (
	CEDULA_EMPLEADO VARCHAR(15) NOT NULL PRIMARY KEY,
	PRIMER_NOMBRE VARCHAR(100) NOT NULL,
	APELLIDO VARCHAR(100) NOT NULL,
	FECHA_INGRESO DATE NOT NULL CHECK (FECHA_INGRESO <= CURRENT_DATE),
	SALARIO_BASE NUMERIC(12, 2) NOT NULL CHECK (SALARIO_BASE > 0),
	ESTADO_LABORAL VARCHAR(20) NOT NULL CHECK (
		ESTADO_LABORAL IN ('activo', 'en_licencia', 'retirado')
	),
	CARGO VARCHAR(30) NOT NULL,
	CORREO_CORP VARCHAR(100) NOT NULL UNIQUE,
	CODIGO_AGENCIA VARCHAR(10) NOT NULL,
	CEDULA_SUPERVISOR VARCHAR(15) NULL,
	FOREIGN KEY (CODIGO_AGENCIA) REFERENCES AGENCIA (CODIGO_AGENCIA),
	FOREIGN KEY (CEDULA_SUPERVISOR) REFERENCES EMPLEADO (CEDULA_EMPLEADO)
);

-- Tabla 10 Cajero
CREATE TABLE CAJERO (
	CEDULA_EMPLEADO VARCHAR(15) NOT NULL PRIMARY KEY,
	NRO_CAJA INTEGER NOT NULL CHECK (NRO_CAJA > 0),
	FOREIGN KEY (CEDULA_EMPLEADO) REFERENCES EMPLEADO (CEDULA_EMPLEADO)
);

-- Tabla 11 Asesor
CREATE TABLE ASESOR (
	CEDULA_EMPLEADO VARCHAR(15) NOT NULL PRIMARY KEY,
	COMISION NUMERIC(5, 2) NOT NULL CHECK (COMISION >= 0),
	FOREIGN KEY (CEDULA_EMPLEADO) REFERENCES EMPLEADO (CEDULA_EMPLEADO)
);

-- Tabla 12 Director_Agencia
CREATE TABLE DIRECTOR_AGENCIA (
	CEDULA_EMPLEADO VARCHAR(15) NOT NULL PRIMARY KEY,
	CLAVE_ACCESO VARCHAR(250) NOT NULL,
	FOREIGN KEY (CEDULA_EMPLEADO) REFERENCES EMPLEADO (CEDULA_EMPLEADO)
);

-- Tabla 13 Empleado_Telefono 
CREATE TABLE EMPLEADO_TELEFONO (
	ID_TEL_EMPLEADO SERIAL NOT NULL PRIMARY KEY,
	CEDULA_EMPLEADO VARCHAR(15) NOT NULL,
	TELEFONO VARCHAR(15) NOT NULL,
	FOREIGN KEY (CEDULA_EMPLEADO) REFERENCES EMPLEADO (CEDULA_EMPLEADO)
);

-- Tabla 14 Atiende
CREATE TABLE ATIENDE (
	CEDULA_EMPLEADO VARCHAR(15) NOT NULL,
	CEDULA_ASOCIADO VARCHAR(15) NOT NULL,
	FECHA_INICIO DATE NOT NULL CHECK (FECHA_INICIO <= CURRENT_DATE),
	PRIMARY KEY (CEDULA_EMPLEADO, CEDULA_ASOCIADO),
	FOREIGN KEY (CEDULA_EMPLEADO) REFERENCES EMPLEADO (CEDULA_EMPLEADO),
	FOREIGN KEY (CEDULA_ASOCIADO) REFERENCES ASOCIADO (CEDULA_ASOCIADO)
);

-- Tabla 15 Credito
CREATE TABLE CREDITO (
	NUMERO_RADICADO VARCHAR(20) NOT NULL PRIMARY KEY,
	VLR_SOLICITADO NUMERIC(15, 2) NOT NULL CHECK (VLR_SOLICITADO > 0),
	VLR_APROBADO NUMERIC(15, 2) NOT NULL CHECK (VLR_APROBADO > 0),
	LINEA_CREDITO VARCHAR(50) NOT NULL CHECK (
		LINEA_CREDITO IN (
			'libre_inversion',
			'vivienda',
			'agropecuario',
			'educativo',
			'empresarial'
		)
	),
	TASA_INTERES NUMERIC(5, 2) NOT NULL CHECK (TASA_INTERES > 0),
	PLAZO_MESES INTEGER NOT NULL CHECK (PLAZO_MESES > 0),
	FECHA_APROBACION DATE NOT NULL CHECK (FECHA_APROBACION <= CURRENT_DATE),
	FECHA_PRIMER_VENCIMIENTO DATE NOT NULL CHECK (FECHA_PRIMER_VENCIMIENTO > FECHA_APROBACION),
	ESTADO_CREDITO VARCHAR(20) NOT NULL CHECK (
		ESTADO_CREDITO IN (
			'en_estudio',
			'aprobado',
			'desembolsado',
			'al_dia',
			'en_mora',
			'cancelado',
			'castigado'
		)
	),
	CEDULA_ASOCIADO VARCHAR(15) NOT NULL,
	CODIGO_AGENCIA VARCHAR(10) NOT NULL,
	FOREIGN KEY (CEDULA_ASOCIADO) REFERENCES ASOCIADO (CEDULA_ASOCIADO),
	FOREIGN KEY (CODIGO_AGENCIA) REFERENCES AGENCIA (CODIGO_AGENCIA)
);

-- Tabla 16 Cuenta_de_Ahorros
CREATE TABLE CUENTA_DE_AHORROS (
	NUMERO_CUENTA VARCHAR(20) NOT NULL PRIMARY KEY,
	FECHA_APERTURA DATE NOT NULL CHECK (FECHA_APERTURA <= CURRENT_DATE),
	ESTADO VARCHAR(20) NOT NULL CHECK (ESTADO IN ('activa', 'inactiva', 'embargada')),
	CEDULA_ASOCIADO VARCHAR(15) NOT NULL,
	CODIGO_AGENCIA VARCHAR(10) NOT NULL,
	FOREIGN KEY (CEDULA_ASOCIADO) REFERENCES ASOCIADO (CEDULA_ASOCIADO),
	FOREIGN KEY (CODIGO_AGENCIA) REFERENCES AGENCIA (CODIGO_AGENCIA)
);

-- Tabla 17 Movimientos
CREATE TABLE MOVIMIENTOS (
	NUMERO_TRANSACCION VARCHAR(20) NOT NULL PRIMARY KEY,
	TIPO_MOVIMIENTO VARCHAR(30) NOT NULL CHECK (
		TIPO_MOVIMIENTO IN (
			'deposito',
			'retiro',
			'transferencia_entrante',
			'transferencia_saliente'
		)
	),
	VALOR NUMERIC(15, 2) NOT NULL CHECK (VALOR > 0),
	CANAL VARCHAR(30) NOT NULL CHECK (
		CANAL IN ('presencial', 'app_movil', 'cajero_automatico')
	),
	FECHA_HORA TIMESTAMP NOT NULL CHECK (FECHA_HORA <= CURRENT_TIMESTAMP),
	NUMERO_CUENTA VARCHAR(20) NOT NULL,
	FOREIGN KEY (NUMERO_CUENTA) REFERENCES CUENTA_DE_AHORROS (NUMERO_CUENTA)
);
-- Tabla 18 Cuotas
CREATE TABLE CUOTAS (
	ID_CUOTA SERIAL NOT NULL PRIMARY KEY,
	NUMERO_CUOTA INTEGER NOT NULL CHECK (NUMERO_CUOTA > 0),
	FECHA_VENCIMIENTO DATE NOT NULL,
	ESTADO_CUOTA VARCHAR(20) NOT NULL CHECK (
		ESTADO_CUOTA IN ('pendiente', 'a_tiempo', 'con_mora')
	),
	NUMERO_RADICADO VARCHAR(20) NOT NULL,
	FOREIGN KEY (NUMERO_RADICADO) REFERENCES CREDITO (NUMERO_RADICADO)
);

-- Tabla 19 Pagos
CREATE TABLE PAGOS (
	ID_PAGO SERIAL NOT NULL PRIMARY KEY,
	FECHA_PAGO DATE NOT NULL CHECK (FECHA_PAGO <= CURRENT_DATE),
	VALOR_PAGADO NUMERIC(15, 2) NOT NULL CHECK (VALOR_PAGADO > 0),
	ESTADO_PAGO VARCHAR(20) NOT NULL CHECK (
		ESTADO_PAGO IN ('a_tiempo', 'con_mora', 'pendiente')
	),
	ID_CUOTA INTEGER NOT NULL,
	FOREIGN KEY (ID_CUOTA) REFERENCES CUOTAS (ID_CUOTA)
);

-- Tabla 20 Codeudora
CREATE TABLE CODEUDORA (
	CEDULA_CODEUDOR VARCHAR(15) NOT NULL,
	NUMERO_RADICADO VARCHAR(20) NOT NULL,
	FECHA_FIRMA DATE NOT NULL CHECK (FECHA_FIRMA <= CURRENT_DATE),
	PRIMARY KEY (CEDULA_CODEUDOR, NUMERO_RADICADO),
	FOREIGN KEY (CEDULA_CODEUDOR) REFERENCES ASOCIADO (CEDULA_ASOCIADO),
	FOREIGN KEY (NUMERO_RADICADO) REFERENCES CREDITO (NUMERO_RADICADO)
);

-- Tabla 21 Supervisa 
CREATE TABLE SUPERVISA (
	CEDULA_SUPERVISOR VARCHAR(15) NOT NULL,
	CEDULA_SUPERVISADO VARCHAR(15) NOT NULL,
	PRIMARY KEY (CEDULA_SUPERVISOR, CEDULA_SUPERVISADO),
	CHECK (CEDULA_SUPERVISOR <> CEDULA_SUPERVISADO),
	FOREIGN KEY (CEDULA_SUPERVISOR) REFERENCES EMPLEADO (CEDULA_EMPLEADO),
	FOREIGN KEY (CEDULA_SUPERVISADO) REFERENCES EMPLEADO (CEDULA_EMPLEADO)
);